### ISSUE TITLE
Research Unit 9-10 and Divide the Topics

### ISSUE THREAD

**Issue by JishnuS420** [CSA-Tri-1/DADDYJlessons#1]
### [Topics ](https://apcentral.collegeboard.org/media/pdf/ap-computer-science-a-course-and-exam-description.pdf#page=148) - Person researching:

9.1 & 10.1 - **David Vasilev**

Student Version: [9.1](https://davidvasilev1.github.io/CSAsite/posts/lessonStudent/) & 10.1
Teacher Version: [9.1](https://davidvasilev1.github.io/CSAsite/posts/lesson/) & 10.1

[9.2 & 9.3](https://drewreed2005.github.io/dre2//2023/10/09/My_U9_Sections_IPYNB_2_.html) - **Drew Reed**

[9.4](https://pitsco.github.io/personal/c4.0/2023/10/23/Unit9.4-Inheritance.html) & 10.2 - **Derrick Huang** 

9.5 & 9.7 - **Jishnu Singiresu**

9.6 -  **Alex Lu**

`wget https://raw.githubusercontent.com/CSA-Tri-1/DADDYJlessons/main/_notebooks/2023-10-31-U10_RecursionStudent.ipynb`

**Comment by drewreed2005** [comment]
![Image](https://github.com/CSA-Tri-1/DADDYJlessons/assets/111479240/21c839c4-ff3e-4107-b5c8-a96639668a9e)
[College Board Page](https://apclassroom.collegeboard.org/8/home?unit=9)

**Comment by drewreed2005** [comment]
```java
class Vehicle {
    public int year;
    public String manufacturer;

    public Vehicle(int year, String manufacturer) { // constructor for parent class
        this.year = year;
        this.manufacturer = manufacturer;
    }

    public Vehicle() { // no-argument constructor with placeholder values
        this.year = 2000;
        this.manufacturer = "Unknown";
    }

    // parent class method
    public void drive() {
        System.out.println("The driver is driving the car.");
    }
}
```
